version: '3.4'

services:
    requestsdb:
        container_name: requestsdb
        ports: 
            - "1433:1433"
        environment:
            SA_PASSWORD: "P!SW0rd123"
            ACCEPT_EULA: "Y"
    requestapp:
        container_name: requestapp
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:Default=Server=requestsdb;Database=RequestsDB;User Id=sa;Password=P!SW0rd123;"
        ports:
            - "5002:80"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        
    ocelotapigatway:
        container_name: ocelotapigatway
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - "5000:80"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
