version: '3.4'

services:
    requestsdb:
        container_name: requestsdb
        ports: 
            - "1433:1433"
        environment:
            SA_PASSWORD: "P!SW0rd123"
            ACCEPT_EULA: "Y"
    requestapp:
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - "ConnectionStrings:Default=Server=requestsdb;Database=RequestsDB;User Id=sa;Password=P!SW0rd123;"
        ports:
            - "5002:80"
            - "5003:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ocelotapigatway:
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
        ports:
            - "5000:80"
            - "5001:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro